[#ICC-81]  Add PN category to getMessage and getMessages (fallback only)
pagopa/io-functions-app-messages pull request #25
Opened 2022-06-01 15:19 UTC by fabriziopapi

Add a new category `PN` to tag third-party messages coming from the service _Piattaforma Notifiche_.
This new catogry will be used only when retrieving the message detail or when retrieving the message list with the fallback method.

#### List of Changes

Update io-fn-commons to the version with the new category
Add a selector to map a category from a service_id
Add the new category to getMessages(fallback) enpoint
Add the new category to getMessage enpoint  

#### Motivation and Context

This change will properly tag a third-party message from PN with a specific category: this will allow the APP to proper identify a PN message in the message list and follow the right user experience specific for PN message.  

#### How Has This Been Tested?

unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-06-01 15:26 UTC, fabriziopapi commented
denpens on https://github.com/pagopa/io-functions-commons/pull/276

2022-06-08 08:19 UTC, AleDore commented on package.json
> +    "@pagopa/io-functions-commons": "^25.2.0",
Maybe we have to upgrade this version once @gquadrati merges new definitions

2022-06-08 12:57 UTC, gquadrati commented on package.json
> +    "@pagopa/io-functions-commons": "^25.2.0",
Sure, version 25.2.1

2022-06-08 15:38 UTC, fabriziopapi commented on package.json
> +    "@pagopa/io-functions-commons": "^25.2.0",
ok, thank you!

2022-06-10 11:20 UTC, gquadrati requested changes
It's fine, just small comments

2022-06-10 11:20 UTC, gquadrati commented on __integrations__/env.ts
> +export const PN_SERVICE_ID = "pn-service-id";
use the one defined in process.env to be aligned with the function one
```suggestion
export const PN_SERVICE_ID = process.env.PN_SERVICE_ID;
```

2022-06-10 11:20 UTC, gquadrati commented on __integrations__/environments/env.function
> +PN_SERVICE_ID="pn-service-id"
Set it in `env.base` file, and reference it here, to be sure we will use the same value everywhere is needed

2022-06-10 11:20 UTC, gquadrati commented on __integrations__/environments/env.integration-tests
> +PN_SERVICE_ID="pn-service-id"
Set it in env.base file, and reference it here

2022-06-10 11:20 UTC, gquadrati commented on __integrations__/package.json
> +    "@types/node": "^13.11.0",
:D 
```suggestion
    "@types/node": "^13.11.0",
```

2022-06-10 11:20 UTC, gquadrati commented on GetMessages/getMessagesFunctions/models.ts
> +    InternalMessageCategoryPn
I think we can safely use fn-commons one.
`InternalMessageCategoryPayment` was necessary because of an intermediate step in which we don't have `rptId` value, just `noticeNumber`.

2022-06-10 11:20 UTC, gquadrati commented on utils/messages.ts
> +  // Partial<typeof ApiNewMessage._A["content"]>;
```suggestion
```

2022-06-10 11:20 UTC, gquadrati commented on utils/messages.ts
> +export const getThirdPartyDataWithCategoryFetcher: (
Can you provide a test?

2022-06-21 09:55 UTC, fabriziopapi commented on __integrations__/environments/env.function
> +PN_SERVICE_ID="pn-service-id"
done, thank you!

2022-06-21 09:55 UTC, fabriziopapi commented on __integrations__/environments/env.integration-tests
> +PN_SERVICE_ID="pn-service-id"
done, thank you!

2022-06-21 10:20 UTC, fabriziopapi commented on GetMessages/getMessagesFunctions/models.ts
> +    InternalMessageCategoryPn
If we replace it with `MessageCategoryPayment` from fn-commons, we must changes existing mapping code in utils.messages.ts->enrichData.
Maybe we could do it in another PR?

2022-06-21 10:42 UTC, fabriziopapi commented on utils/messages.ts
> +export const getThirdPartyDataWithCategoryFetcher: (
done. thank you!

2022-06-22 12:16 UTC, AleDore approved these changes, later dismissed
LGTM

2022-06-27 10:14 UTC, fabriziopapi commented on GetMessages/getMessagesFunctions/models.ts
> +    InternalMessageCategoryPn
ok, as stated by Greta, we could avoit to redefine the InternalMessageCategoryPn

2022-06-27 10:21 UTC, gquadrati approved these changes
LGTM

2022-06-27 12:29 UTC, merged