[#IOCOM-708] precondition flag management
pagopa/io-functions-app-messages pull request #45
Opened 2023-12-13 22:01 UTC by Garma00

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-18 16:45 UTC, michaeldisaro approved these changes, later dismissed

2024-01-08 16:21 UTC, michaeldisaro requested changes

2024-01-08 16:21 UTC, michaeldisaro commented on __integrations__/__mocks__/fixtures.ts
> +  maybeRemoeContentCosmosParameters: O.Option<ClientAndDbName>
typo

2024-01-08 16:21 UTC, michaeldisaro commented on __integrations__/__mocks__/fixtures.ts
> +    TE.map(_ => log(`${_.length} Remote content created`)),
I'd give a name to _

2024-01-08 16:21 UTC, michaeldisaro commented on __integrations__/__mocks__/fixtures.ts
> +    TE.mapLeft(_ => {
ditto

2024-01-09 13:28 UTC, Garma00 commented on __integrations__/__mocks__/fixtures.ts
> +    TE.map(_ => log(`${_.length} Remote content created`)),
[f8293a6](https://github.com/pagopa/io-functions-app-messages/pull/45/commits/f8293a6ffb27fe52da557c7fa0c48df2487f73de)

2024-01-09 13:28 UTC, Garma00 commented on __integrations__/__mocks__/fixtures.ts
> +    TE.mapLeft(_ => {
[f8293a6](https://github.com/pagopa/io-functions-app-messages/pull/45/commits/f8293a6ffb27fe52da557c7fa0c48df2487f73de)

2024-01-10 10:41 UTC, michaeldisaro approved these changes

2024-01-10 13:25 UTC, merged