[#IOCOM-921] new function GetRCConfiguration
pagopa/io-functions-app-messages pull request #47
Opened 2024-01-25 15:22 UTC by acuiuli

#### List of Changes

- [new function GetRCConfiguration](https://github.com/pagopa/io-functions-app-messages/commit/e503a4e7a3174b6850b01d024466b3c83f889eaf)

#### Motivation and Context

Created a new function to retrieve the remote content configuration by ID

#### How Has This Been Tested?

Unit test

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-01-26 11:06 UTC, Garma00 requested changes
Well done, just some comments 😃

2024-01-26 11:06 UTC, Garma00 commented on GetRCConfiguration/index.ts
> +  "v1/remote-contents/configurations/{id}",
The path should start with `/api` [for example](https://github.com/pagopa/io-functions-app-messages/blob/master/GetMessage/index.ts#L56)

2024-01-26 11:06 UTC, Garma00 commented on GetRCConfiguration/index.ts
> +import { cosmosdbInstance } from "../utils/cosmosdb";
Take care, here we want to use the cosmos instance for remote content see [here](https://github.com/pagopa/io-functions-app-messages/blob/master/utils/cosmosdb.ts#L32)

2024-01-26 11:06 UTC, Garma00 commented on GetRCConfiguration/handler.ts
> +export function GetRCConfiguration(
What about using an arrow function here and remove the eslint-disable?
Also i would suggest to stat the name of the function without the capital "G" for convention

2024-01-26 11:06 UTC, Garma00 commented on GetRCConfiguration/handler.ts
> +export const GetRCConfigurationHandler = (
I would start the name without the capital "G" for convention

2024-01-26 11:06 UTC, Garma00 commented on utils/remoteContentConfig.ts
> +      x => TE.right(O.some(x))
I would use something like `remoteConfiguration` to rename `x`

2024-01-31 13:41 UTC, acuiuli commented on GetRCConfiguration/handler.ts
> +export const GetRCConfigurationHandler = (
All the other handlers in the functions of this repo also start with a capital letter, so I followed it. Check it [here](https://github.com/pagopa/io-functions-app-messages/blob/33ab4864da15fbb500542d957bd07fbc270fe112/GetMessages/handler.ts#L63C14-L63C32) and [here](https://github.com/pagopa/io-functions-app-messages/blob/33ab4864da15fbb500542d957bd07fbc270fe112/GetMessage/handler.ts#L142)

2024-01-31 16:08 UTC, michaeldisaro approved these changes
LGTM

2024-01-31 16:09 UTC, Garma00 approved these changes
lgtm

2024-02-01 13:42 UTC, merged